import ContactForm from "./components/contactForm";

import './globals.css'

import { Inter } from "next/font/google";
import NavBar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title:
    "Sphere Remodeling | Las Vegas-Henderson Home Remodeling and Renovation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <NavBar />
        {children}
      <ContactForm />
        </body>
    </html>
  );
}
